services:
    db:
        image: postgres:17-alpine
        restart: always
        environment:
            POSTGRES_DB: "$DB_NAME"
            POSTGRES_USER: "$DB_USER"
            POSTGRES_PASSWORD: "$DB_PASSWORD"
        ports:
            - "$DB_PORT:$DB_PORT"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "$PORT:$PORT"
        depends_on:
            db:
                condition: service_healthy
        environment:
            - NODE_ENV=production

volumes:
    postgres_data:
